Resources:
  bis3datalakeFAC9D748:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: BigDataBiS3RedshiftStack/bi-s3-data-lake/Resource
  CopyS3toRedshiftHandlerServiceRoleDE5CD56A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: BigDataBiS3RedshiftStack/CopyS3toRedshiftHandler/ServiceRole/Resource
  CopyS3toRedshiftHandlerCFDEF2B0:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dacS3Bucket14069B7F
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dacS3VersionKeyBCF48C4E
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dacS3VersionKeyBCF48C4E
      Handler: copyS3toRedshift.handler
      Role:
        Fn::GetAtt:
          - CopyS3toRedshiftHandlerServiceRoleDE5CD56A
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          S3_DATA_LAKE:
            Ref: bis3datalakeFAC9D748
      Timeout: 600
    DependsOn:
      - CopyS3toRedshiftHandlerServiceRoleDE5CD56A
    Metadata:
      aws:cdk:path: BigDataBiS3RedshiftStack/CopyS3toRedshiftHandler/Resource
      aws:asset:path: /Users/antonrunhaar/ShellStack/Repositories/big-data-bi-s3-redshift/lambda/copyS3toRedshift
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.27.0,@aws-cdk/assets=1.32.2,@aws-cdk/aws-cloudwatch=1.32.2,@aws-cdk/aws-ec2=1.32.2,@aws-cdk/aws-events=1.32.2,@aws-cdk/aws-iam=1.32.2,@aws-cdk/aws-kms=1.32.2,@aws-cdk/aws-lambda=1.32.2,@aws-cdk/aws-logs=1.32.2,@aws-cdk/aws-s3=1.32.2,@aws-cdk/aws-s3-assets=1.32.2,@aws-cdk/aws-sqs=1.32.2,@aws-cdk/aws-ssm=1.32.2,@aws-cdk/core=1.32.2,@aws-cdk/cx-api=1.32.2,@aws-cdk/region-info=1.32.2,jsii-runtime=node.js/v12.16.1
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dacS3Bucket14069B7F:
    Type: String
    Description: S3 bucket for asset "29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dac"
  AssetParameters29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dacS3VersionKeyBCF48C4E:
    Type: String
    Description: S3 key for asset version "29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dac"
  AssetParameters29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dacArtifactHash8BD17B0E:
    Type: String
    Description: Artifact hash for asset "29228f17b72e3d87bb342e207934d51ef55f602e13fefd4c405016b948897dac"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

